# This file specifies your Python application's runtime configuration.
# See https://cloud.google.com/appengine/docs/managed-vms/config for details.
runtime: custom
vm: true
api_version: 1
module: default

resources:
  cpu: .5
  memory_gb: 1.3
  disk_size_gb: 10

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.5

beta_settings:
  service_account_scopes: >
    https://www.googleapis.com/auth/userinfo.email,
    https://www.googleapis.com/auth/cloud-platform

env_variables:
  PYTHON_ENV: production
  LOG_PATH: /var/log/app_engine/custom_logs
